version: '3'

services:
  web:
    build: 
      context: .
    container_name: agil
    restart: always
    environment:
      - TZ=Asia/Jakarta
    ports:
      - 8100:80
    volumes:
      - ./app:/var/www/html
    